# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "WhereAreYou.xcworkspace", scheme: "WhereAreYou")
    increment_build_number(xcodeproj: "WhereAreYou.xcodeproj")
    upload_to_app_store(
      force: true,
      skip_screenshots: true,
			skip_metadata: false,
      submit_for_review: true,
      automatic_release: false,
      submission_information: {
        add_id_info_serves_ads: false,
        add_id_info_tracks_action: true,
        add_id_info_tracks_install: true,
        add_id_info_uses_idfa: true
      }
    )

    slack(
      message: "App Store 배포 완료",
      slack_url: "https://hooks.slack.com/services/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"
    )
  end
end
